package(
    default_visibility = ["//:santa_package_group"],
    features = ["-layering_check"],
)

licenses(["notice"])

filegroup(
  name="santa_dev",
  srcs=["Santa_Dev.provisionprofile"]
)

filegroup(
  name="daemon_dev",
  srcs=["Santa_Daemon_Dev.provisionprofile"],
)
