licenses(["notice"])

filegroup(
    name = "binaryrules_testdata",
    srcs = glob(["binaryrules/*"]),
    visibility = ["//:santa_package_group"],
)

filegroup(
    name = "protobuf_json_testdata",
    srcs = glob(["protobuf/**/*.json"]),
    visibility = ["//:santa_package_group"],
)
