clean_sync = true
client_mode = "MONITOR"
batch_size = 100

[[rules]]
rule_type = "BINARY"
policy = "BLOCKLIST"
identifier = "432ad7907dbcfb2ddc0552a398b2c78539c1a230468d87f914f650e061756dbd"
custom_msg = "deny bad test binary"

[[rules]]
rule_type = "CERTIFICATE"
policy = "BLOCKLIST"
identifier = "6a7767fb80ac25fd073db8302cb50bea36512808e045bbc3768659bf503d4d31"
custom_msg = "deny bad test self-signed cert"
