objc_library(
    name = "configuration_helper",
    srcs = [
        "MacOSVirtualMachineConfigurationHelper.m",
    ],
    hdrs = [
        "MacOSVirtualMachineConfigurationHelper.h",
    ],
    sdk_frameworks = [
        "Virtualization",
    ],
    visibility = [
        "//Testing/integration/VM:__subpackages__",
    ],
)

objc_library(
    name = "delegate",
    srcs = [
        "MacOSVirtualMachineDelegate.m",
    ],
    hdrs = [
        "MacOSVirtualMachineDelegate.h",
    ],
    sdk_frameworks = [
        "Virtualization",
    ],
    visibility = [
        "//Testing/integration/VM:__subpackages__",
    ],
)

objc_library(
    name = "error",
    hdrs = [
        "Error.h",
    ],
    visibility = [
        "//Testing/integration/VM:__subpackages__",
    ],
)
