name: Check Markdown

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
    - name: "check for trailing whitespace and newlines"
      run: "! git grep -EIn $'[ \t]+$' -- ':(exclude)*.patch'"
