name: Check Markdown

on:
  pull_request:
    paths:
      - "**.md"

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Santa"
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
      - name: "Check for deadlinks"
        uses: lycheeverse/lychee-action@2b973e86fc7b1f6b36a93795fe2c9c6ae1118621 # ratchet:lycheeverse/lychee-action@v1
        with:
          fail: true
      - name: "Check for trailing whitespace and newlines"
        run: "! git grep -EIn $'[ \t]+$' -- ':(exclude)*.patch'"
