name: continuous
on:
  schedule:
    - cron: '* 10 * * *' # Every day at 10:00 UTC
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  preqs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checks for flaky tests
        run: bazel test --test_strategy=exclusive --test_output=errors --runs_per_test 50 -t- :unit_tests --define=SANTA_BUILD_TYPE=adhoc
