name: Fuzzing

on:
  schedule:
    - cron: '0 6 * * *' # Every day at 6:00 UTC
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  start_vm:
    runs-on: e2e-host
    steps:
      - uses: actions/checkout@v3
      - name: Start VM
        run: python3 Testing/integration/actions/start_vm.py macOS_13.bundle.tar.gz

  fuzz:
    runs-on: e2e-vm
    steps:
      - uses: actions/checkout@v3
      - name: Setup libfuzzer
        run: Fuzzing/install_libclang_fuzzer.sh
      - name: Fuzz
        run: |
          for target in $(bazel query 'kind(fuzzing_launcher, //Fuzzing:all)'); do
            bazel run --config=fuzz $target -- -- -max_len=32768 -runs=1000000 -timeout=5
          done
      - name: Upload crashes
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: artifacts
          path: /tmp/fuzzing/artifacts
      - name: Poweroff VM
        if: ${{ always() }}
        run: sudo shutdown -h +1
